using FinalProject_Team12.Models;
using FinalProject_Team12.DAL;
using System.Data.Entity.Migrations;
using System;
using System.Linq;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace FinalProject_Team12.Migrations
{
	public class CustomerData
	{
		public void SeedCustomers(AppDbContext db)
		{
            AppUserManager UserManager = new AppUserManager(new UserStore<AppUser>(db));
            AppUser c1 = new AppUser();
			c1.PasswordHash = "hello1";
			c1.LastName = "Baker";
			c1.FirstName = "Christopher";
			c1.MiddleInitial = "L.";
			c1.Birthday = new DateTime(1949, 11, 23);
			c1.Street = "1245 Lake Anchorage Blvd.";
			c1.City = "Austin";
			c1.State = "TX";
			c1.ZipCode = 78705;
			c1.PhoneNumber = "5125550180";
			c1.Email = "cbaker@example.com";
			db.Users.AddOrUpdate(c => c.Email, c1);
			db.SaveChanges();
			c1 = db.Users.FirstOrDefault(c => c.Email == "cbaker@example.com");
			UserManager.AddToRole(c1.Id, "Customer");
			db.SaveChanges();

			AppUser c2 = new AppUser();
			c2.PasswordHash = "potato";
			c2.LastName = "Banks";
			c2.FirstName = "Michelle";
			c2.MiddleInitial = "";
			c2.Birthday = new DateTime(1962, 11, 27);
			c2.Street = "1300 Tall Pine Lane";
			c2.City = "Austin";
			c2.State = "TX";
			c2.ZipCode = 78712;
			c2.PhoneNumber = "5125550183";
			c2.Email = "banker@longhorn.net";
			db.Users.AddOrUpdate(c => c.Email, c2);
			db.SaveChanges();
			c2 = db.Users.FirstOrDefault(c => c.Email == "banker@longhorn.net");
			UserManager.AddToRole(c2.Id, "Customer");
			db.SaveChanges();

			AppUser c3 = new AppUser();
			c3.PasswordHash = "painting";
			c3.LastName = "Broccolo";
			c3.FirstName = "Franco";
			c3.MiddleInitial = "V";
			c3.Birthday = new DateTime(1992, 10, 11);
			c3.Street = "62 Browning Road";
			c3.City = "Austin";
			c3.State = "TX";
			c3.ZipCode = 78704;
			c3.PhoneNumber = "5125550128";
			c3.Email = "franco@example.com";
			db.Users.AddOrUpdate(c => c.Email, c3);
			db.SaveChanges();
			c3 = db.Users.FirstOrDefault(c => c.Email == "franco@example.com");
			UserManager.AddToRole(c3.Id, "Customer");
			db.SaveChanges();

			AppUser c4 = new AppUser();
			c4.PasswordHash = "texas1";
			c4.LastName = "Chang";
			c4.FirstName = "Wendy";
			c4.MiddleInitial = "L";
			c4.Birthday = new DateTime(1997, 5, 16);
			c4.Street = "202 Bellmont Hall";
			c4.City = "Round Rock";
			c4.State = "TX";
			c4.ZipCode = 78681;
			c4.PhoneNumber = "5125550133";
			c4.Email = "wchang@example.com";
			db.Users.AddOrUpdate(c => c.Email, c4);
			db.SaveChanges();
			c4 = db.Users.FirstOrDefault(c => c.Email == "wchang@example.com");
			UserManager.AddToRole(c4.Id, "Customer");
			db.SaveChanges();

			AppUser c5 = new AppUser();
			c5.PasswordHash = "Anchorage";
			c5.LastName = "Chou";
			c5.FirstName = "Lim";
			c5.MiddleInitial = "";
			c5.Birthday = new DateTime(1970, 4, 6);
			c5.Street = "1600 Teresa Lane";
			c5.City = "Austin";
			c5.State = "TX";
			c5.ZipCode = 78705;
			c5.PhoneNumber = "5125550102";
			c5.Email = "limchou@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c5);
			db.SaveChanges();
			c5 = db.Users.FirstOrDefault(c => c.Email == "limchou@gogle.com");
			UserManager.AddToRole(c5.Id, "Customer");
			db.SaveChanges();

			AppUser c6 = new AppUser();
			c6.PasswordHash = "pepperoni";
			c6.LastName = "Dixon";
			c6.FirstName = "Shan";
			c6.MiddleInitial = "D";
			c6.Birthday = new DateTime(1984, 1, 12);
			c6.Street = "234 Holston Circle";
			c6.City = "Austin";
			c6.State = "TX";
			c6.ZipCode = 78712;
			c6.PhoneNumber = "5125550146";
			c6.Email = "shdixon@aoll.com";
			db.Users.AddOrUpdate(c => c.Email, c6);
			db.SaveChanges();
			c6 = db.Users.FirstOrDefault(c => c.Email == "shdixon@aoll.com");
			UserManager.AddToRole(c6.Id, "Customer");
			db.SaveChanges();

			AppUser c7 = new AppUser();
			c7.PasswordHash = "longhorns";
			c7.LastName = "Evans";
			c7.FirstName = "Jim Bob";
			c7.MiddleInitial = "";
			c7.Birthday = new DateTime(1959, 9, 9);
			c7.Street = "506 Farrell Circle";
			c7.City = "Georgetown";
			c7.State = "TX";
			c7.ZipCode = 78628;
			c7.PhoneNumber = "5125550170";
			c7.Email = "j.b.evans@aheca.org";
			db.Users.AddOrUpdate(c => c.Email, c7);
			db.SaveChanges();
			c7 = db.Users.FirstOrDefault(c => c.Email == "j.b.evans@aheca.org");
			UserManager.AddToRole(c7.Id, "Customer");
			db.SaveChanges();

			AppUser c8 = new AppUser();
			c8.PasswordHash = "aggies";
			c8.LastName = "Feeley";
			c8.FirstName = "Lou Ann";
			c8.MiddleInitial = "K";
			c8.Birthday = new DateTime(2001, 1, 12);
			c8.Street = "600 S 8th Street W";
			c8.City = "Austin";
			c8.State = "TX";
			c8.ZipCode = 78746;
			c8.PhoneNumber = "5125550105";
			c8.Email = "feeley@penguin.org";
			db.Users.AddOrUpdate(c => c.Email, c8);
			db.SaveChanges();
			c8 = db.Users.FirstOrDefault(c => c.Email == "feeley@penguin.org");
			UserManager.AddToRole(c8.Id, "Customer");
			db.SaveChanges();

			AppUser c9 = new AppUser();
			c9.PasswordHash = "raiders";
			c9.LastName = "Freeley";
			c9.FirstName = "Tesa";
			c9.MiddleInitial = "P";
			c9.Birthday = new DateTime(1991, 2, 4);
			c9.Street = "4448 Fairview Ave.";
			c9.City = "Horseshoe Bay";
			c9.State = "TX";
			c9.ZipCode = 78657;
			c9.PhoneNumber = "5125550114";
			c9.Email = "tfreeley@minnetonka.ci.us";
			db.Users.AddOrUpdate(c => c.Email, c9);
			db.SaveChanges();
			c9 = db.Users.FirstOrDefault(c => c.Email == "tfreeley@minnetonka.ci.us");
			UserManager.AddToRole(c9.Id, "Customer");
			db.SaveChanges();

			AppUser c10 = new AppUser();
			c10.PasswordHash = "mustangs";
			c10.LastName = "Garcia";
			c10.FirstName = "Margaret";
			c10.MiddleInitial = "L";
			c10.Birthday = new DateTime(1991, 10, 2);
			c10.Street = "594 Longview";
			c10.City = "Austin";
			c10.State = "TX";
			c10.ZipCode = 78727;
			c10.PhoneNumber = "5125550155";
			c10.Email = "mgarcia@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c10);
			db.SaveChanges();
			c10 = db.Users.FirstOrDefault(c => c.Email == "mgarcia@gogle.com");
			UserManager.AddToRole(c10.Id, "Customer");
			db.SaveChanges();

			AppUser c11 = new AppUser();
			c11.PasswordHash = "onetime";
			c11.LastName = "Haley";
			c11.FirstName = "Charles";
			c11.MiddleInitial = "E";
			c11.Birthday = new DateTime(1974, 7, 10);
			c11.Street = "One Cowboy Pkwy";
			c11.City = "Austin";
			c11.State = "TX";
			c11.ZipCode = 78712;
			c11.PhoneNumber = "5125550116";
			c11.Email = "chaley@thug.com";
			db.Users.AddOrUpdate(c => c.Email, c11);
			db.SaveChanges();
			c11 = db.Users.FirstOrDefault(c => c.Email == "chaley@thug.com");
			UserManager.AddToRole(c11.Id, "Customer");
			db.SaveChanges();

			AppUser c12 = new AppUser();
			c12.PasswordHash = "hampton1";
			c12.LastName = "Hampton";
			c12.FirstName = "Jeffrey";
			c12.MiddleInitial = "T.";
			c12.Birthday = new DateTime(2004, 3, 10);
			c12.Street = "337 38th St.";
			c12.City = "San Marcos";
			c12.State = "TX";
			c12.ZipCode = 78666;
			c12.PhoneNumber = "5125550150";
			c12.Email = "jeffh@sonic.com";
			db.Users.AddOrUpdate(c => c.Email, c12);
			db.SaveChanges();
			c12 = db.Users.FirstOrDefault(c => c.Email == "jeffh@sonic.com");
			UserManager.AddToRole(c12.Id, "Customer");
			db.SaveChanges();

			AppUser c13 = new AppUser();
			c13.PasswordHash = "jhearn22";
			c13.LastName = "Hearn";
			c13.FirstName = "John";
			c13.MiddleInitial = "B";
			c13.Birthday = new DateTime(1950, 8, 5);
			c13.Street = "4225 North First";
			c13.City = "Austin";
			c13.State = "TX";
			c13.ZipCode = 78705;
			c13.PhoneNumber = "5125550196";
			c13.Email = "wjhearniii@umich.org";
			db.Users.AddOrUpdate(c => c.Email, c13);
			db.SaveChanges();
			c13 = db.Users.FirstOrDefault(c => c.Email == "wjhearniii@umich.org");
			UserManager.AddToRole(c13.Id, "Customer");
			db.SaveChanges();

			AppUser c14 = new AppUser();
			c14.PasswordHash = "hickhickup";
			c14.LastName = "Hicks";
			c14.FirstName = "Anthony";
			c14.MiddleInitial = "J";
			c14.Birthday = new DateTime(2004, 12, 8);
			c14.Street = "32 NE Garden Ln., Ste 910";
			c14.City = "Austin";
			c14.State = "TX";
			c14.ZipCode = 78712;
			c14.PhoneNumber = "5125550188";
			c14.Email = "ahick@yaho.com";
			db.Users.AddOrUpdate(c => c.Email, c14);
			db.SaveChanges();
			c14 = db.Users.FirstOrDefault(c => c.Email == "ahick@yaho.com");
			UserManager.AddToRole(c14.Id, "Customer");
			db.SaveChanges();

			AppUser c15 = new AppUser();
			c15.PasswordHash = "ingram2015";
			c15.LastName = "Ingram";
			c15.FirstName = "Brad";
			c15.MiddleInitial = "S.";
			c15.Birthday = new DateTime(2001, 9, 5);
			c15.Street = "6548 La Posada Ct.";
			c15.City = "New York";
			c15.State = "NY";
			c15.ZipCode = 10101;
			c15.PhoneNumber = "5125550116";
			c15.Email = "ingram@jack.com";
			db.Users.AddOrUpdate(c => c.Email, c15);
			db.SaveChanges();
			c15 = db.Users.FirstOrDefault(c => c.Email == "ingram@jack.com");
			UserManager.AddToRole(c15.Id, "Customer");
			db.SaveChanges();

			AppUser c16 = new AppUser();
			c16.PasswordHash = "toddy25";
			c16.LastName = "Jacobs";
			c16.FirstName = "Todd";
			c16.MiddleInitial = "L.";
			c16.Birthday = new DateTime(1999, 1, 20);
			c16.Street = "4564 Elm St.";
			c16.City = "Austin";
			c16.State = "TX";
			c16.ZipCode = 78729;
			c16.PhoneNumber = "5125550166";
			c16.Email = "toddj@yourmom.com";
			db.Users.AddOrUpdate(c => c.Email, c16);
			db.SaveChanges();
			c16 = db.Users.FirstOrDefault(c => c.Email == "toddj@yourmom.com");
			UserManager.AddToRole(c16.Id, "Customer");
			db.SaveChanges();

			AppUser c17 = new AppUser();
			c17.PasswordHash = "something";
			c17.LastName = "Lawrence";
			c17.FirstName = "Victoria";
			c17.MiddleInitial = "M.";
			c17.Birthday = new DateTime(2000, 4, 14);
			c17.Street = "6639 Butterfly Ln.";
			c17.City = "Beverly Hills";
			c17.State = "CA";
			c17.ZipCode = 90210;
			c17.PhoneNumber = "5125550173";
			c17.Email = "thequeen@aska.net";
			db.Users.AddOrUpdate(c => c.Email, c17);
			db.SaveChanges();
			c17 = db.Users.FirstOrDefault(c => c.Email == "thequeen@aska.net");
			UserManager.AddToRole(c17.Id, "Customer");
			db.SaveChanges();

			AppUser c18 = new AppUser();
			c18.PasswordHash = "Password1";
			c18.LastName = "Lineback";
			c18.FirstName = "Erik";
			c18.MiddleInitial = "W";
			c18.Birthday = new DateTime(2003, 12, 2);
			c18.Street = "1300 Netherland St";
			c18.City = "Austin";
			c18.State = "TX";
			c18.ZipCode = 78758;
			c18.PhoneNumber = "5125550167";
			c18.Email = "linebacker@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c18);
			db.SaveChanges();
			c18 = db.Users.FirstOrDefault(c => c.Email == "linebacker@gogle.com");
			UserManager.AddToRole(c18.Id, "Customer");
			db.SaveChanges();

			AppUser c19 = new AppUser();
			c19.PasswordHash = "aclfest2017";
			c19.LastName = "Lowe";
			c19.FirstName = "Ernest";
			c19.MiddleInitial = "S";
			c19.Birthday = new DateTime(1977, 12, 7);
			c19.Street = "3201 Pine Drive";
			c19.City = "New Braunfels";
			c19.State = "TX";
			c19.ZipCode = 78130;
			c19.PhoneNumber = "5125550187";
			c19.Email = "elowe@netscare.net";
			db.Users.AddOrUpdate(c => c.Email, c19);
			db.SaveChanges();
			c19 = db.Users.FirstOrDefault(c => c.Email == "elowe@netscare.net");
			UserManager.AddToRole(c19.Id, "Customer");
			db.SaveChanges();

			AppUser c20 = new AppUser();
			c20.PasswordHash = "nothinggood";
			c20.LastName = "Luce";
			c20.FirstName = "Chuck";
			c20.MiddleInitial = "B";
			c20.Birthday = new DateTime(1949, 3, 16);
			c20.Street = "2345 Rolling Clouds";
			c20.City = "Cactus";
			c20.State = "TX";
			c20.ZipCode = 79013;
			c20.PhoneNumber = "5125550141";
			c20.Email = "cluce@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c20);
			db.SaveChanges();
			c20 = db.Users.FirstOrDefault(c => c.Email == "cluce@gogle.com");
			UserManager.AddToRole(c20.Id, "Customer");
			db.SaveChanges();

			AppUser c21 = new AppUser();
			c21.PasswordHash = "whatever";
			c21.LastName = "MacLeod";
			c21.FirstName = "Jennifer";
			c21.MiddleInitial = "D.";
			c21.Birthday = new DateTime(1947, 2, 21);
			c21.Street = "2504 Far West Blvd.";
			c21.City = "Marble Falls";
			c21.State = "TX";
			c21.ZipCode = 78654;
			c21.PhoneNumber = "5125550185";
			c21.Email = "mackcloud@george.com";
			db.Users.AddOrUpdate(c => c.Email, c21);
			db.SaveChanges();
			c21 = db.Users.FirstOrDefault(c => c.Email == "mackcloud@george.com");
			UserManager.AddToRole(c21.Id, "Customer");
			db.SaveChanges();

			AppUser c22 = new AppUser();
			c22.PasswordHash = "whocares";
			c22.LastName = "Markham";
			c22.FirstName = "Elizabeth";
			c22.MiddleInitial = "P.";
			c22.Birthday = new DateTime(1972, 3, 20);
			c22.Street = "7861 Chevy Chase";
			c22.City = "Kissimmee";
			c22.State = "FL";
			c22.ZipCode = 34741;
			c22.PhoneNumber = "5125550134";
			c22.Email = "cmartin@beets.com";
			db.Users.AddOrUpdate(c => c.Email, c22);
			db.SaveChanges();
			c22 = db.Users.FirstOrDefault(c => c.Email == "cmartin@beets.com");
			UserManager.AddToRole(c22.Id, "Customer");
			db.SaveChanges();

			AppUser c23 = new AppUser();
			c23.PasswordHash = "xcellent";
			c23.LastName = "Martin";
			c23.FirstName = "Clarence";
			c23.MiddleInitial = "A";
			c23.Birthday = new DateTime(1992, 7, 19);
			c23.Street = "87 Alcedo St.";
			c23.City = "Austin";
			c23.State = "TX";
			c23.ZipCode = 78709;
			c23.PhoneNumber = "5125550151";
			c23.Email = "clarence@yoho.com";
			db.Users.AddOrUpdate(c => c.Email, c23);
			db.SaveChanges();
			c23 = db.Users.FirstOrDefault(c => c.Email == "clarence@yoho.com");
			UserManager.AddToRole(c23.Id, "Customer");
			db.SaveChanges();

			AppUser c24 = new AppUser();
			c24.PasswordHash = "snowsnow";
			c24.LastName = "Martinez";
			c24.FirstName = "Gregory";
			c24.MiddleInitial = "R.";
			c24.Birthday = new DateTime(1947, 5, 28);
			c24.Street = "8295 Sunset Blvd.";
			c24.City = "Red Rock";
			c24.State = "TX";
			c24.ZipCode = 78662;
			c24.PhoneNumber = "5125550120";
			c24.Email = "gregmartinez@drdre.com";
			db.Users.AddOrUpdate(c => c.Email, c24);
			db.SaveChanges();
			c24 = db.Users.FirstOrDefault(c => c.Email == "gregmartinez@drdre.com");
			UserManager.AddToRole(c24.Id, "Customer");
			db.SaveChanges();

			AppUser c25 = new AppUser();
			c25.PasswordHash = "mydogspot";
			c25.LastName = "Miller";
			c25.FirstName = "Charles";
			c25.MiddleInitial = "R.";
			c25.Birthday = new DateTime(1990, 10, 15);
			c25.Street = "8962 Main St.";
			c25.City = "South Padre Island";
			c25.State = "TX";
			c25.ZipCode = 78597;
			c25.PhoneNumber = "5125550198";
			c25.Email = "cmiller@bob.com";
			db.Users.AddOrUpdate(c => c.Email, c25);
			db.SaveChanges();
			c25 = db.Users.FirstOrDefault(c => c.Email == "cmiller@bob.com");
			UserManager.AddToRole(c25.Id, "Customer");
			db.SaveChanges();

			AppUser c26 = new AppUser();
			c26.PasswordHash = "spotmydog";
			c26.LastName = "Nelson";
			c26.FirstName = "Kelly";
			c26.MiddleInitial = "T";
			c26.Birthday = new DateTime(1971, 7, 13);
			c26.Street = "2601 Red River";
			c26.City = "Disney";
			c26.State = "OK";
			c26.ZipCode = 74340;
			c26.PhoneNumber = "5125550177";
			c26.Email = "knelson@aoll.com";
			db.Users.AddOrUpdate(c => c.Email, c26);
			db.SaveChanges();
			c26 = db.Users.FirstOrDefault(c => c.Email == "knelson@aoll.com");
			UserManager.AddToRole(c26.Id, "Customer");
			db.SaveChanges();

			AppUser c27 = new AppUser();
			c27.PasswordHash = "joejoejoe";
			c27.LastName = "Nguyen";
			c27.FirstName = "Joe";
			c27.MiddleInitial = "C";
			c27.Birthday = new DateTime(1984, 3, 17);
			c27.Street = "1249 4th SW St.";
			c27.City = "Del Rio";
			c27.State = "TX";
			c27.ZipCode = 78841;
			c27.PhoneNumber = "5125550174";
			c27.Email = "joewin@xfactor.com";
			db.Users.AddOrUpdate(c => c.Email, c27);
			db.SaveChanges();
			c27 = db.Users.FirstOrDefault(c => c.Email == "joewin@xfactor.com");
			UserManager.AddToRole(c27.Id, "Customer");
			db.SaveChanges();

			AppUser c28 = new AppUser();
			c28.PasswordHash = "billyboy";
			c28.LastName = "O'Reilly";
			c28.FirstName = "Bill";
			c28.MiddleInitial = "T";
			c28.Birthday = new DateTime(1959, 7, 8);
			c28.Street = "8800 Gringo Drive";
			c28.City = "Austin";
			c28.State = "TX";
			c28.ZipCode = 78746;
			c28.PhoneNumber = "5125550167";
			c28.Email = "orielly@foxnews.cnn";
			db.Users.AddOrUpdate(c => c.Email, c28);
			db.SaveChanges();
			c28 = db.Users.FirstOrDefault(c => c.Email == "orielly@foxnews.cnn");
			UserManager.AddToRole(c28.Id, "Customer");
			db.SaveChanges();

			AppUser c29 = new AppUser();
			c29.PasswordHash = "radgirl";
			c29.LastName = "Radkovich";
			c29.FirstName = "Anka";
			c29.MiddleInitial = "L";
			c29.Birthday = new DateTime(1966, 5, 19);
			c29.Street = "1300 Elliott Pl";
			c29.City = "Austin";
			c29.State = "TX";
			c29.ZipCode = 78712;
			c29.PhoneNumber = "5125550151";
			c29.Email = "ankaisrad@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c29);
			db.SaveChanges();
			c29 = db.Users.FirstOrDefault(c => c.Email == "ankaisrad@gogle.com");
			UserManager.AddToRole(c29.Id, "Customer");
			db.SaveChanges();

			AppUser c30 = new AppUser();
			c30.PasswordHash = "meganr34";
			c30.LastName = "Rhodes";
			c30.FirstName = "Megan";
			c30.MiddleInitial = "C.";
			c30.Birthday = new DateTime(1965, 3, 12);
			c30.Street = "4587 Enfield Rd.";
			c30.City = "Austin";
			c30.State = "TX";
			c30.ZipCode = 78705;
			c30.PhoneNumber = "5125550133";
			c30.Email = "megrhodes@freserve.co.uk";
			db.Users.AddOrUpdate(c => c.Email, c30);
			db.SaveChanges();
			c30 = db.Users.FirstOrDefault(c => c.Email == "megrhodes@freserve.co.uk");
			UserManager.AddToRole(c30.Id, "Customer");
			db.SaveChanges();

			AppUser c31 = new AppUser();
			c31.PasswordHash = "ricearoni";
			c31.LastName = "Rice";
			c31.FirstName = "Eryn";
			c31.MiddleInitial = "M.";
			c31.Birthday = new DateTime(1975, 4, 28);
			c31.Street = "3405 Rio Grande";
			c31.City = "Austin";
			c31.State = "TX";
			c31.ZipCode = 78785;
			c31.PhoneNumber = "5125550196";
			c31.Email = "erynrice@aoll.com";
			db.Users.AddOrUpdate(c => c.Email, c31);
			db.SaveChanges();
			c31 = db.Users.FirstOrDefault(c => c.Email == "erynrice@aoll.com");
			UserManager.AddToRole(c31.Id, "Customer");
			db.SaveChanges();

			AppUser c32 = new AppUser();
			c32.PasswordHash = "jrod2017";
			c32.LastName = "Rodriguez";
			c32.FirstName = "Jorge";
			c32.MiddleInitial = "";
			c32.Birthday = new DateTime(1953, 12, 8);
			c32.Street = "6788 Cotter Street";
			c32.City = "Littlefield";
			c32.State = "TX";
			c32.ZipCode = 79339;
			c32.PhoneNumber = "5125550141";
			c32.Email = "jorge@noclue.com";
			db.Users.AddOrUpdate(c => c.Email, c32);
			db.SaveChanges();
			c32 = db.Users.FirstOrDefault(c => c.Email == "jorge@noclue.com");
			UserManager.AddToRole(c32.Id, "Customer");
			db.SaveChanges();

			AppUser c33 = new AppUser();
			c33.PasswordHash = "rogerthat";
			c33.LastName = "Rogers";
			c33.FirstName = "Allen";
			c33.MiddleInitial = "B.";
			c33.Birthday = new DateTime(1973, 4, 22);
			c33.Street = "4965 Oak Hill";
			c33.City = "Austin";
			c33.State = "TX";
			c33.ZipCode = 78733;
			c33.PhoneNumber = "5125550189";
			c33.Email = "mrrogers@lovelyday.com";
			db.Users.AddOrUpdate(c => c.Email, c33);
			db.SaveChanges();
			c33 = db.Users.FirstOrDefault(c => c.Email == "mrrogers@lovelyday.com");
			UserManager.AddToRole(c33.Id, "Customer");
			db.SaveChanges();

			AppUser c34 = new AppUser();
			c34.PasswordHash = "bunnyhop";
			c34.LastName = "Saint-Jean";
			c34.FirstName = "Olivier";
			c34.MiddleInitial = "M";
			c34.Birthday = new DateTime(1995, 2, 19);
			c34.Street = "255 Toncray Dr.";
			c34.City = "Austin";
			c34.State = "TX";
			c34.ZipCode = 78755;
			c34.PhoneNumber = "5125550152";
			c34.Email = "stjean@athome.com";
			db.Users.AddOrUpdate(c => c.Email, c34);
			db.SaveChanges();
			c34 = db.Users.FirstOrDefault(c => c.Email == "stjean@athome.com");
			UserManager.AddToRole(c34.Id, "Customer");
			db.SaveChanges();

			AppUser c35 = new AppUser();
			c35.PasswordHash = "penguin12";
			c35.LastName = "Saunders";
			c35.FirstName = "Sarah";
			c35.MiddleInitial = "J.";
			c35.Birthday = new DateTime(1978, 2, 19);
			c35.Street = "332 Avenue C";
			c35.City = "Austin";
			c35.State = "TX";
			c35.ZipCode = 78701;
			c35.PhoneNumber = "5125550146";
			c35.Email = "saunders@pen.com";
			db.Users.AddOrUpdate(c => c.Email, c35);
			db.SaveChanges();
			c35 = db.Users.FirstOrDefault(c => c.Email == "saunders@pen.com");
			UserManager.AddToRole(c35.Id, "Customer");
			db.SaveChanges();

			AppUser c36 = new AppUser();
			c36.PasswordHash = "alaskaboy";
			c36.LastName = "Sewell";
			c36.FirstName = "William";
			c36.MiddleInitial = "T.";
			c36.Birthday = new DateTime(2004, 12, 23);
			c36.Street = "2365 51st St.";
			c36.City = "El Paso";
			c36.State = "TX";
			c36.ZipCode = 79953;
			c36.PhoneNumber = "5125550192";
			c36.Email = "willsheff@email.com";
			db.Users.AddOrUpdate(c => c.Email, c36);
			db.SaveChanges();
			c36 = db.Users.FirstOrDefault(c => c.Email == "willsheff@email.com");
			UserManager.AddToRole(c36.Id, "Customer");
			db.SaveChanges();

			AppUser c37 = new AppUser();
			c37.PasswordHash = "martin1234";
			c37.LastName = "Sheffield";
			c37.FirstName = "Martin";
			c37.MiddleInitial = "J.";
			c37.Birthday = new DateTime(1960, 5, 8);
			c37.Street = "3886 Avenue A";
			c37.City = "Balmorhea";
			c37.State = "TX";
			c37.ZipCode = 79718;
			c37.PhoneNumber = "5125550131";
			c37.Email = "sheffiled@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c37);
			db.SaveChanges();
			c37 = db.Users.FirstOrDefault(c => c.Email == "sheffiled@gogle.com");
			UserManager.AddToRole(c37.Id, "Customer");
			db.SaveChanges();

			AppUser c38 = new AppUser();
			c38.PasswordHash = "smitty444";
			c38.LastName = "Smith";
			c38.FirstName = "John";
			c38.MiddleInitial = "A";
			c38.Birthday = new DateTime(1955, 6, 25);
			c38.Street = "23 Hidden Forge Dr.";
			c38.City = "Austin";
			c38.State = "TX";
			c38.ZipCode = 78760;
			c38.PhoneNumber = "5125550190";
			c38.Email = "johnsmith187@aoll.com";
			db.Users.AddOrUpdate(c => c.Email, c38);
			db.SaveChanges();
			c38 = db.Users.FirstOrDefault(c => c.Email == "johnsmith187@aoll.com");
			UserManager.AddToRole(c38.Id, "Customer");
			db.SaveChanges();

			AppUser c39 = new AppUser();
			c39.PasswordHash = "dustydusty";
			c39.LastName = "Stroud";
			c39.FirstName = "Dustin";
			c39.MiddleInitial = "P";
			c39.Birthday = new DateTime(1967, 7, 26);
			c39.Street = "1212 Rita Rd";
			c39.City = "Austin";
			c39.State = "TX";
			c39.ZipCode = 78734;
			c39.PhoneNumber = "5125550157";
			c39.Email = "dustroud@mail.com";
			db.Users.AddOrUpdate(c => c.Email, c39);
			db.SaveChanges();
			c39 = db.Users.FirstOrDefault(c => c.Email == "dustroud@mail.com");
			UserManager.AddToRole(c39.Id, "Customer");
			db.SaveChanges();

			AppUser c40 = new AppUser();
			c40.PasswordHash = "stewball";
			c40.LastName = "Stuart";
			c40.FirstName = "Eric";
			c40.MiddleInitial = "D.";
			c40.Birthday = new DateTime(1947, 12, 4);
			c40.Street = "5576 Toro Ring";
			c40.City = "Kyle";
			c40.State = "TX";
			c40.ZipCode = 78640;
			c40.PhoneNumber = "5125550191";
			c40.Email = "estuart@anchor.net";
			db.Users.AddOrUpdate(c => c.Email, c40);
			db.SaveChanges();
			c40 = db.Users.FirstOrDefault(c => c.Email == "estuart@anchor.net");
			UserManager.AddToRole(c40.Id, "Customer");
			db.SaveChanges();

			AppUser c41 = new AppUser();
			c41.PasswordHash = "slowwind";
			c41.LastName = "Stump";
			c41.FirstName = "Peter";
			c41.MiddleInitial = "L";
			c41.Birthday = new DateTime(1974, 7, 10);
			c41.Street = "1300 Kellen Circle";
			c41.City = "Philadelphia";
			c41.State = "PA";
			c41.ZipCode = 19123;
			c41.PhoneNumber = "5125550136";
			c41.Email = "peterstump@noclue.com";
			db.Users.AddOrUpdate(c => c.Email, c41);
			db.SaveChanges();
			c41 = db.Users.FirstOrDefault(c => c.Email == "peterstump@noclue.com");
			UserManager.AddToRole(c41.Id, "Customer");
			db.SaveChanges();

			AppUser c42 = new AppUser();
			c42.PasswordHash = "tanner5454";
			c42.LastName = "Tanner";
			c42.FirstName = "Jeremy";
			c42.MiddleInitial = "S.";
			c42.Birthday = new DateTime(1944, 1, 11);
			c42.Street = "4347 Almstead";
			c42.City = "Austin";
			c42.State = "TX";
			c42.ZipCode = 78747;
			c42.PhoneNumber = "5125550170";
			c42.Email = "jtanner@mustang.net";
			db.Users.AddOrUpdate(c => c.Email, c42);
			db.SaveChanges();
			c42 = db.Users.FirstOrDefault(c => c.Email == "jtanner@mustang.net");
			UserManager.AddToRole(c42.Id, "Customer");
			db.SaveChanges();

			AppUser c43 = new AppUser();
			c43.PasswordHash = "allyrally";
			c43.LastName = "Taylor";
			c43.FirstName = "Allison";
			c43.MiddleInitial = "R.";
			c43.Birthday = new DateTime(1990, 11, 14);
			c43.Street = "467 Nueces St.";
			c43.City = "Austin";
			c43.State = "TX";
			c43.ZipCode = 78712;
			c43.PhoneNumber = "5125550160";
			c43.Email = "taylordjay@aoll.com";
			db.Users.AddOrUpdate(c => c.Email, c43);
			db.SaveChanges();
			c43 = db.Users.FirstOrDefault(c => c.Email == "taylordjay@aoll.com");
			UserManager.AddToRole(c43.Id, "Customer");
			db.SaveChanges();

			AppUser c44 = new AppUser();
			c44.PasswordHash = "taylorbaylor";
			c44.LastName = "Taylor";
			c44.FirstName = "Rachel";
			c44.MiddleInitial = "K.";
			c44.Birthday = new DateTime(1976, 1, 18);
			c44.Street = "345 Longview Dr.";
			c44.City = "Austin";
			c44.State = "TX";
			c44.ZipCode = 78758;
			c44.PhoneNumber = "5125550127";
			c44.Email = "rtaylor@gogle.com";
			db.Users.AddOrUpdate(c => c.Email, c44);
			db.SaveChanges();
			c44 = db.Users.FirstOrDefault(c => c.Email == "rtaylor@gogle.com");
			UserManager.AddToRole(c44.Id, "Customer");
			db.SaveChanges();

			AppUser c45 = new AppUser();
			c45.PasswordHash = "teeoff22";
			c45.LastName = "Tee";
			c45.FirstName = "Frank";
			c45.MiddleInitial = "J";
			c45.Birthday = new DateTime(1998, 9, 6);
			c45.Street = "5590 Lavell Dr";
			c45.City = "Austin";
			c45.State = "TX";
			c45.ZipCode = 78729;
			c45.PhoneNumber = "5125550161";
			c45.Email = "teefrank@noclue.com";
			db.Users.AddOrUpdate(c => c.Email, c45);
			db.SaveChanges();
			c45 = db.Users.FirstOrDefault(c => c.Email == "teefrank@noclue.com");
			UserManager.AddToRole(c45.Id, "Customer");
			db.SaveChanges();

			AppUser c46 = new AppUser();
			c46.PasswordHash = "tucksack1";
			c46.LastName = "Tucker";
			c46.FirstName = "Clent";
			c46.MiddleInitial = "J";
			c46.Birthday = new DateTime(1943, 2, 25);
			c46.Street = "312 Main St.";
			c46.City = "Round Rock";
			c46.State = "TX";
			c46.ZipCode = 78665;
			c46.PhoneNumber = "5125550106";
			c46.Email = "ctucker@alphabet.co.uk";
			db.Users.AddOrUpdate(c => c.Email, c46);
			db.SaveChanges();
			c46 = db.Users.FirstOrDefault(c => c.Email == "ctucker@alphabet.co.uk");
			UserManager.AddToRole(c46.Id, "Customer");
			db.SaveChanges();

			AppUser c47 = new AppUser();
			c47.PasswordHash = "meow88";
			c47.LastName = "Velasco";
			c47.FirstName = "Allen";
			c47.MiddleInitial = "G";
			c47.Birthday = new DateTime(1985, 9, 10);
			c47.Street = "679 W. 4th";
			c47.City = "Cedar Park";
			c47.State = "TX";
			c47.ZipCode = 78613;
			c47.PhoneNumber = "5125550170";
			c47.Email = "avelasco@yoho.com";
			db.Users.AddOrUpdate(c => c.Email, c47);
			db.SaveChanges();
			c47 = db.Users.FirstOrDefault(c => c.Email == "avelasco@yoho.com");
			UserManager.AddToRole(c47.Id, "Customer");
			db.SaveChanges();

			AppUser c48 = new AppUser();
			c48.PasswordHash = "vinovino";
			c48.LastName = "Vino";
			c48.FirstName = "Janet";
			c48.MiddleInitial = "E";
			c48.Birthday = new DateTime(1985, 2, 7);
			c48.Street = "189 Grape Road";
			c48.City = "Lockhart";
			c48.State = "TX";
			c48.ZipCode = 78644;
			c48.PhoneNumber = "5125550128";
			c48.Email = "vinovino@grapes.com";
			db.Users.AddOrUpdate(c => c.Email, c48);
			db.SaveChanges();
			c48 = db.Users.FirstOrDefault(c => c.Email == "vinovino@grapes.com");
			UserManager.AddToRole(c48.Id, "Customer");
			db.SaveChanges();

			AppUser c49 = new AppUser();
			c49.PasswordHash = "gowest";
			c49.LastName = "West";
			c49.FirstName = "Jake";
			c49.MiddleInitial = "T";
			c49.Birthday = new DateTime(1976, 1, 9);
			c49.Street = "RR 3287";
			c49.City = "Austin";
			c49.State = "TX";
			c49.ZipCode = 78705;
			c49.PhoneNumber = "2025550170";
			c49.Email = "westj@pioneer.net";
			db.Users.AddOrUpdate(c => c.Email, c49);
			db.SaveChanges();
			c49 = db.Users.FirstOrDefault(c => c.Email == "westj@pioneer.net");
			UserManager.AddToRole(c49.Id, "Customer");
			db.SaveChanges();

			AppUser c50 = new AppUser();
			c50.PasswordHash = "louielouie";
			c50.LastName = "Winthorpe";
			c50.FirstName = "Louis";
			c50.MiddleInitial = "L";
			c50.Birthday = new DateTime(1953, 4, 19);
			c50.Street = "2500 Padre Blvd";
			c50.City = "Austin";
			c50.State = "TX";
			c50.ZipCode = 78747;
			c50.PhoneNumber = "2025550141";
			c50.Email = "winner@hootmail.com";
			db.Users.AddOrUpdate(c => c.Email, c50);
			db.SaveChanges();
			c50 = db.Users.FirstOrDefault(c => c.Email == "winner@hootmail.com");
			UserManager.AddToRole(c50.Id, "Customer");
			db.SaveChanges();

			AppUser c51 = new AppUser();
			c51.PasswordHash = "woodyman1";
			c51.LastName = "Wood";
			c51.FirstName = "Reagan";
			c51.MiddleInitial = "B.";
			c51.Birthday = new DateTime(2002, 12, 28);
			c51.Street = "447 Westlake Dr.";
			c51.City = "Austin";
			c51.State = "TX";
			c51.ZipCode = 78753;
			c51.PhoneNumber = "2025550128";
			c51.Email = "rwood@voyager.net";
			db.Users.AddOrUpdate(c => c.Email, c51);
			db.SaveChanges();
			c51 = db.Users.FirstOrDefault(c => c.Email == "rwood@voyager.net");
			UserManager.AddToRole(c51.Id, "Customer");
			db.SaveChanges();

		}
	}
}
